//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharsooWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.children = new HashSet<Category>();
            this.DependentCategories = new HashSet<Category>();
            this.Puzzles = new HashSet<Puzzle>();
            this.UserPuzzles = new HashSet<UserPuzzle>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public int Price { get; set; }
        public bool Visit { get; set; }
        public int Row { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> PrerequisiteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Category> children { get; set; }
        internal virtual Category Parent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Category> DependentCategories { get; set; }
        internal virtual Category PrerequisitCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Puzzle> Puzzles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPuzzle> UserPuzzles { get; set; }
    }
}
