//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharsooWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayerInfo()
        {
            this.LogIns = new HashSet<LogIn>();
            this.Purchases = new HashSet<Purchase>();
            this.PuzzleRates = new HashSet<PuzzleRate>();
        }
    
        public int PlayerID { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int CoinCount { get; set; }
        public bool Dirty { get; set; }
        public bool HasDubler { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<LogIn> LogIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PuzzleRate> PuzzleRates { get; set; }
    }
}
