//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharsooWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerPuzzle
    {
        public System.DateTime Time { get; set; }
        public System.DateTimeOffset Duration { get; set; }
        public int MoveCount { get; set; }
        public short HintCount1 { get; set; }
        public bool Success { get; set; }
        public short HintCount2 { get; set; }
        public short HintCount3 { get; set; }
        public int PlayerID { get; set; }
        public int PuzzleID { get; set; }
    
        internal virtual Puzzle Puzzle { get; set; }
        internal virtual PlayerInfo PlayerInfo { get; set; }
    }
}
