//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharsooWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushID
    {
        public int PlayerID { get; set; }
        public string PID { get; set; }
    
        internal virtual PlayerInfo PlayerInfo { get; set; }
    }
}
