//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CharsooWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int RewardID { get; set; }
        public int PlayerID { get; set; }
        public int RewardAmount { get; set; }
        public string RewardCouse { get; set; }
        public System.DateTime LastUpdate { get; set; }
    }
}
